services:
  cli-app:
    container_name: cli-app
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - database
    stdin_open: true  # Permite entrada interativa
    tty: true         # Aloca um terminal pseudo-TTY
    command: sh -c "sleep 3; python main.py; exec sh"

  database:
    container_name: database
    image: postgres:13
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST: ${DATABASE_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: